version: "3.8"

services:

  redis-local:
    image: redis
    volumes:
      - 'redis-data:/data'
    networks:
      - demo_net
    ports:
      - 6379:6379
      
  webapp_demo:
    build: 
      context: .
    networks:
      - demo_net
    ports:
      - 8082:80

volumes:
  redis-data:

networks:
  demo_net: